### ISSUE TITLE
Under some unknown circumstance, the module disable DsN and never enable it back

### ISSUE THREAD

**Issue by JiDW** [jessev14/Multiattack-5e#1]
Hello,

I'm the developer of Dice So Nice. I've tracked an issue reported by multiple users to your module, causing the users to not be able to see 3D dice anymore.

It looks like your mobile sometimes needs to disable DsN and re-enable it alter, but in some case (unknown) it never enables it back.

I hope you can track this issue down! 
If you can't find out why, another way for you to fix this issue would be to use the "rollStart" hook from DsN where you can hide a DsN roll by setting "blind" to true: https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/wikis/API/Hooks#dicesonicerollstart

Regards.

**Comment by jessev14** [comment]
Hi! Thanks for the heads up!

I'll push out a hotfix that'll remove the `game.settings.set("dice-so-nice", "enabled", false);` line.
Do you think I should also add a line in the init hook: `game.settings.set("dice-so-nice", "enabled", true);` to re-enable DSN for users that have it disabled?

I use the rollStart hook with "blind" in another part of this module that involves Better Rolls 5e and it works fine.
But for some reason, I couldn't figure out how to make this approach work for this part of the module that implements Midi compatibility. 
My guess is some new update of Midi broke my messy workaround using `game.settings.set("dice-so-nice", "enabled", true);`

I'll see if I can figure out the rollStart hook method and use that everywhere instead.

**Comment by jessev14** [comment]
I just released a new version that removed all instances of `game.settings.set("dice-so-nice", "enabled", false);`.

I'm now using the DsN RollStart hook to `blind: true` all the rolls I want to hide.

This should hopefully prevent any of these kind of issues from coming up again.

Thanks again for letting me know and sorry for the trouble on your end! Please let me know if you get any more issue reports!

**Comment by JiDW** [comment]
Thanks! That was super quick :)

**Comment by JiDW** [comment]
> Do you think I should also add a line in the init hook: game.settings.set("dice-so-nice", "enabled", true); to re-enable DSN for users that have it disabled?

Probably not, as it may conflict with another module. I'll just share with them the line to re-enable Dice so Nice, no worries.

**Comment by jessev14** [comment]
> > Do you think I should also add a line in the init hook: game.settings.set("dice-so-nice", "enabled", true); to re-enable DSN for users that have it disabled?
> 
> Probably not, as it may conflict with another module. I'll just share with them the line to re-enable Dice so Nice, no worries.

Yeah I realized that had the potential to break a lot of things so I decided against it.
I also included the re-enable code in the latest update notes for this release to hopefully get more users to see it if they need it.
