### ISSUE TITLE
Potential New Feature

### ISSUE THREAD

**Issue by joro8425** [jessev14/Multiattack-5e#12]
Hello! Thank you so much for creating this module, it has made my life as a DM so much more efficient, and the life of my monk player much less chaotic!

I was wondering if it would be possible to make an addition to the module that would allow situational bonuses, like the Bless modifier for attack rolls, apply to all multiattack rolls. At the moment it appears to only give the bonus to the first roll in the list. 

Example: the Monkey made two attacks. Both of which were supposed to have a flat +4 to hit modifier, which was entered as "+4" into the situation bonus field when the attack was made, but one can see mathematically that it was only applied to the first attack roll. 
![result](https://user-images.githubusercontent.com/25331981/172914812-7cf80e42-9d78-4879-ba37-f96188e14e70.PNG)
(2+6+3+4 = 15, however 12+6+3+4 =/= 21, rather the output should be 25)

If this is something that already is possible and I am just being obtuse, please let me know! Thanks again for your module and contribution to the Foundry community. I hope you have a lovely day.

**Comment by jessev14** [comment]
this is actually a bug. the situational bonus should apply to all rolls. ill take a look

**Comment by joro8425** [comment]
Oh, good to know! Thank you so much! I'll keep an eye out for any changes.

**Comment by jessev14** [comment]
I haven't forgotten about this, but unfortunately it's not a bug that I think I can fix in the current version of dnd5e. Fortunately, the system contributors are going to implement a lot of helpful tools in version 2.0.0 of dnd5e which will make fixing this bug easier.

**Comment by jessev14** [comment]
Finally got around to this. In version 7.0.0 (only for Foundry V10), situational bonuses will apply to all rolls.
