### ISSUE TITLE
Update to v10

### ISSUE THREAD

**Issue by CaosFR** [jessev14/Multiattack-5e#14]
Hi,

Thanks for your module and work. Does it possible to update the module for the v10 ?

In the module.json I can see :

```
  "minimumCoreVersion": "9",
  "compatibleCoreVersion": "9",
```

Happy dev

**Comment by brunocalado** [comment]
update to v10 plz

**Comment by jessev14** [comment]
Unfortunately have to prioritize paid commission work in my free time.

Feel free to donate to support the development efforts.
