### ISSUE TITLE
Possible Compatibility with MidiQol?

### ISSUE THREAD

**Issue by ZetFalcon** [jessev14/Multiattack-5e#2]
Hi! Wanna ask if possible to solve the compatibility issue with MidiQol, as it would be great to have both modules running togethers without the continues error messages. Thanks for your time, really appreciate your module ^^

**Comment by jessev14** [comment]
Midi-QOL compatibility is definitely possible (it is already implemented in previous versions). I was waiting for a stable Midi-QOL release before making this new version compatible, but I don't use Midi-QOL so I don't keep up with the module. Is it all set to go for 0.8.6?

**Comment by ZetFalcon** [comment]
MidiQol Already ship the 0.8.6 update, as you can check it in the FoundryVTT page ^^

**Comment by ZetFalcon** [comment]
It was updated 5hs ago https://gitlab.com/tposney/midi-qol ^^

**Comment by jessev14** [comment]
Re-implemented in version `5.2.0`.
