### ISSUE TITLE
Dice so Nice! do not hide multiattack 5e

### ISSUE THREAD

**Issue by CepheiA2** [jessev14/Multiattack-5e#3]
Using Dice so Nice! module, and multiattack 5e, gm rolls are hidden in chat, but not their animation.

Is possible to fix it?

**Comment by jessev14** [comment]
Ah that's some bad lack of oversight. I'll have a fix for that out soon. Thanks for reporting.

**Comment by CepheiA2** [comment]
Ty mate, me and my friends appreciate your work


Il lun 14 giu 2021, 10:18 jessev14 ***@***.***> ha scritto:

**Comment by jessev14** [comment]
I have the fix ready to be published, but note that there is an issue in core Foundry v0.8.6 that may cause multiattack/extra attack chat cards to be visible to all users even if the roll was made as a Private GM roll. This issue should be addressed in core Foundry v0.8.7: https://gitlab.com/foundrynet/foundryvtt/-/issues/5302
