### ISSUE TITLE
Midi Compatibility issue

### ISSUE THREAD

**Issue by Bfrench6** [jessev14/Multiattack-5e#4]
When trying to use the multiattack function in a macro along with midi, the results are not whats expected (see screenshot, should deal 22 and 10 damage, but deals 15 and 10 instead, which are the damage values from the second attack only). This issue does not occur when using the multiattack button from the token controls interface.
![image](https://user-images.githubusercontent.com/12520977/122458194-8a1dc300-cf7d-11eb-9eb8-789d52615a71.png)
![image](https://user-images.githubusercontent.com/12520977/122458269-a15cb080-cf7d-11eb-9e1b-53fbd4634c33.png)

**Comment by jessev14** [comment]
can I see what your macro looks like?

**Comment by Bfrench6** [comment]
const weapons = ["Vermin Fang", "Vermin Fang"]; // Make two attacks
game.MA5e.multiattack(weapons); // rollType and actor arguments are optional (default to "attack" and "canvas.tokens.controlled[0].actor" respectively)

I copied it basically directly from your example, just got rid of the rolltype and actor since the defaults were fine

**Comment by jessev14** [comment]
ah okay, this is on me. that code is for non-BR / non-Midi users.
For Midi, try this:
```js
const weapons = ["Vermin Fang", "Vermin Fang"];
game.MA5e.midiMA5e(weapons, actor); // actor is REQUIRED
```
I'll update the readme with this info.

**Comment by Bfrench6** [comment]
Oh great, thanks. New macro works perfectly.
