### ISSUE TITLE
Error in MidiQol MA5e macro: SyntaxError: Identifier 'actor' has already been declared

### ISSUE THREAD

**Issue by jocolamarco** [jessev14/Multiattack-5e#5]
FVTT: 0.8.8
DnD5e: 1.3.6
MidiQol: 0.8.29
**MA5e: 5.2.1 (latest)**

Description: 
Steps:
1 - Create macro (adapted from "For Midi-QOL:" section in README.md)
2 - Edit to have the right name of the attack for the select actor and save
3 - Target another actor and Run the macro
4 - Error message is shown:

![image](https://user-images.githubusercontent.com/45291719/124480534-47425480-dd9f-11eb-967c-938927e5827a.png)

Macro:
```
const weapons = ["Touch", "Touch"]; // Make two longsword attacks and one dagger attack
const actor = canvas.tokens.controlled[0].actor; // GM users could pre-define multiattack rolls for various actors
game.MA5e.midiMA5e(weapons,actor) // actor argument is optional (default set to "canvas.tokens.controlled[0].actor); note that this function is ASYNC
```

**Comment by jessev14** [comment]
Is this the full macro? Is there any other code in the macro you're executing?
