### ISSUE TITLE
Better Rolls - Extra Crit Damage not rolled

### ISSUE THREAD

**Issue by CallMeDevill** [jessev14/Multiattack-5e#6]
FoundryVtt Version : 0.8.9
5e System : 1.5.3

Description : 
Items with Extra Critical Damage are rolled fine with a normal roll

![image](https://user-images.githubusercontent.com/39500206/141875590-cdb164b1-93b3-4a7a-8f41-74b31fb86e55.png)
--current weapon config--

![image](https://user-images.githubusercontent.com/39500206/141875614-ca4f2f50-2293-4554-adac-ce8ca1297479.png)
--chat output with a default BetterRolls roll--

When used with Multiattack 5e the extra critical damage is not added

![image](https://user-images.githubusercontent.com/39500206/141875713-71f79d3b-2dc1-4922-bab3-ae602e800e89.png)
--chat output with Multiattack roll--

**Comment by jessev14** [comment]
This will be fixed in version 6.0.0 of the module.

**Comment by StefanPrisacariu** [comment]
Nice, thanks for the info ^^ 
I am CallMeDevill, secondary account
