### ISSUE TITLE
Incompatability with Minimal Rolling Enhancements (MRE) for D&D5e

### ISSUE THREAD

**Issue by 346184** [jessev14/Multiattack-5e#7]
As discussed on Discord, this module is currently incompatible with [Minimal Rolling Enhancements (MRE)](https://github.com/ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E).

If both are enabled, the vanilla FoundryVTT roll popup dialog can still be brought up, but the modification adding the dropdown to select number of attacks to roll isn't there.

(Issue in the MRE repo: https://github.com/ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E/issues/12)

**Comment by jessev14** [comment]
v6.0.0 should now be compatible with MRE.

**Comment by zerastos** [comment]
Thanks for fixing it!
