### ISSUE TITLE
Support with foundry v9.X

### ISSUE THREAD

**Issue by CaosFR** [jessev14/Multiattack-5e#8]
Hi,

Simple question that many would like to know. Is your module compatible with v9.X? Have any tests been carried out?

I'm refer to : https://docs.google.com/spreadsheets/d/1ppPR348igxL75M_G7dWl3otzXYpPwrnj7NVSDP8GmVw/edit#gid=0

Thanks
Bests regards

**Comment by jessev14** [comment]
I delayed the v9 update because a simple bug in the dnd5e system that prevents the module from working hasn't been addressed yet. 
But I recently figured out the bug fix myself, which I'll bundle with the module and release soon.

**Comment by CaosFR** [comment]
Thanks for your quick reply :)
