### ISSUE TITLE
Not seeing additional attacks for player

### ISSUE THREAD

**Issue by ravingdragoon** [jessev14/Multiattack-5e#9]
Is there specific settings that need to be set in Midi-QoL for the extra attacks option to be inserted into the PC attack roll dialog box?  I am able to get the workflow to work properly by using the multi-attack button and/or setting defaults and then attacking, but I never see an option in the pop up, after clicking attack in the chat dialog box, to indicate how many attacks to roll. I do not see any errors at all in the dev console.

Also, I am not seeing the chat cards getting merged. Are there specific settings for that as well?

**Comment by jessev14** [comment]
In version `6.1.0`, you'll be able to set the number of rolls as long as "Enable roll automation support" is disabled in Midi.
